# Generated by Django 4.2.7 on 2025-09-26 04:57

import demos.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Demo Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('video_file', models.FileField(upload_to=demos.models.demo_video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv'])], verbose_name='Video File')),
                ('thumbnail', models.ImageField(upload_to=demos.models.demo_thumbnail_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Thumbnail Image')),
                ('duration', models.DurationField(blank=True, help_text='Duration in HH:MM:SS format', null=True, verbose_name='Duration')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views Count')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Likes Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Demo',
                'verbose_name_plural': 'Demos',
                'db_table': 'demos',
                'ordering': ['-is_featured', 'sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Emoji or CSS icon class', max_length=50, verbose_name='Icon')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demo Category',
                'verbose_name_plural': 'Demo Categories',
                'db_table': 'demo_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('morning', 'Morning (9:30 AM - 1:00 PM)'), ('afternoon', 'Afternoon/Evening (2:00 PM - 7:00 PM)')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'db_table': 'time_slots',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField(verbose_name='Requested Date')),
                ('confirmed_date', models.DateField(blank=True, null=True, verbose_name='Confirmed Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes/Additional Details')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_requests', to='demos.timeslot', verbose_name='Confirmed Time Slot')),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_requests', to='demos.demo')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_demo_requests', to=settings.AUTH_USER_MODEL, verbose_name='Handled By')),
                ('requested_time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demos.timeslot', verbose_name='Requested Time Slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demo Request',
                'verbose_name_plural': 'Demo Requests',
                'db_table': 'demo_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='demo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demos', to='demos.democategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='demo',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_demos', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.CreateModel(
            name='DemoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('watch_duration', models.DurationField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_views', to='demos.demo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demo View',
                'verbose_name_plural': 'Demo Views',
                'db_table': 'demo_views',
                'ordering': ['-viewed_at'],
                'unique_together': {('demo', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DemoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_likes', to='demos.demo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demo Like',
                'verbose_name_plural': 'Demo Likes',
                'db_table': 'demo_likes',
                'ordering': ['-liked_at'],
                'unique_together': {('demo', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DemoFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1-5)')),
                ('feedback_text', models.TextField(verbose_name='Feedback')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='demos.demo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demo Feedback',
                'verbose_name_plural': 'Demo Feedbacks',
                'db_table': 'demo_feedbacks',
                'ordering': ['-created_at'],
                'unique_together': {('demo', 'user')},
            },
        ),
    ]
