# Generated by Django 4.2.7 on 2025-09-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='country_region',
            field=models.CharField(blank=True, max_length=5, verbose_name='Country/Region'),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='is_international',
            field=models.BooleanField(default=False, verbose_name='International Customer'),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal/ZIP Code'),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Timezone'),
        ),
    ]
