# Generated by Django 4.2.7 on 2025-09-27 09:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demos', '0002_demorequest_city_demorequest_country_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='target_customers',
            field=models.ManyToManyField(blank=True, help_text='Select specific customers who can access this demo. Leave empty for all customers.', related_name='accessible_demos', to=settings.AUTH_USER_MODEL, verbose_name='Target Customers'),
        ),
    ]
