# Generated by Django 4.2.7 on 2025-09-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0003_demo_target_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
