# Generated by Django 4.2.7 on 2025-09-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailotp'),
        ('demos', '0004_alter_demo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='business_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demos', to='accounts.businesscategory', verbose_name='Business Category'),
        ),
        migrations.AddField(
            model_name='demo',
            name='business_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demos', to='accounts.businesssubcategory', verbose_name='Business Subcategory'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demos', to='demos.democategory', verbose_name='Category'),
        ),
    ]
