# Generated by Django 4.2.7 on 2025-09-30 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailotp'),
        ('demos', '0005_demo_business_category_demo_business_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='business_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_requests', to='accounts.businesscategory', verbose_name='Business Category'),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='business_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_requests', to='accounts.businesssubcategory', verbose_name='Business Subcategory'),
        ),
    ]
