# Generated by Django 4.2.7 on 2025-09-30 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailotp'),
        ('demos', '0006_demorequest_business_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='business_category',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='business_subcategory',
        ),
        migrations.AddField(
            model_name='demo',
            name='target_business_categories',
            field=models.ManyToManyField(blank=True, help_text='Select business categories this demo is relevant for. Leave empty for all categories.', related_name='available_demos', to='accounts.businesscategory', verbose_name='Target Business Categories'),
        ),
        migrations.AddField(
            model_name='demo',
            name='target_business_subcategories',
            field=models.ManyToManyField(blank=True, help_text='Select specific subcategories this demo is relevant for. Leave empty for all subcategories.', related_name='available_demos', to='accounts.businesssubcategory', verbose_name='Target Business Subcategories'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='demos', to='demos.democategory', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
