# Generated by Django 4.2.7 on 2025-09-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0007_remove_demo_business_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='category',
        ),
        migrations.AddField(
            model_name='demo',
            name='demo_type',
            field=models.CharField(choices=[('product', 'Product Demo'), ('feature', 'Feature Demo'), ('overview', 'Overview Demo'), ('tutorial', 'Tutorial'), ('case_study', 'Case Study'), ('webinar', 'Webinar Recording')], default='product', max_length=20, verbose_name='Demo Type'),
        ),
    ]
