# Generated by Django 4.2.7 on 2025-10-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0008_remove_demo_category_demo_demo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demorequest',
            name='country_region',
            field=models.CharField(blank=True, default='IN', max_length=50, null=True, verbose_name='Country/Region'),
        ),
    ]
