# Generated by Django 4.2.7 on 2025-10-03 10:38

import demos.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0009_alter_demorequest_country_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='file_type',
            field=models.CharField(choices=[('video', 'Video'), ('webgl', 'WebGL')], default='video', help_text='Select whether this is a video demo or WebGL interactive demo', max_length=10, verbose_name='File Type'),
        ),
        migrations.AddField(
            model_name='demo',
            name='webgl_file',
            field=models.FileField(blank=True, help_text='Upload WebGL file - HTML, ZIP archive, or 3D model (required if file type is WebGL)', null=True, upload_to=demos.models.demo_webgl_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html', 'zip', 'gltf', 'glb'])], verbose_name='WebGL File'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration in HH:MM:SS format (applicable for videos only)', null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as suggested demo to highlight for customers', verbose_name='Featured/Suggested'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (required if file type is Video)', null=True, upload_to=demos.models.demo_video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv'])], verbose_name='Video File'),
        ),
    ]
