# Generated by Django 4.2.7 on 2025-10-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0010_demo_file_type_demo_webgl_file_alter_demo_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='extracted_path',
            field=models.CharField(blank=True, help_text='Path to extracted WebGL files (auto-populated)', max_length=500, verbose_name='Extracted Path'),
        ),
    ]
