# Generated by Django 4.2.7 on 2025-10-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0011_demo_extracted_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='cancellation_details',
            field=models.TextField(blank=True, null=True, verbose_name='Cancellation Details'),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('scheduling_conflict', 'Scheduling Conflict'), ('requirements_change', 'Change in Requirements'), ('found_alternative', 'Found Alternative Solution'), ('no_longer_interested', 'No Longer Interested'), ('other', 'Other Reasons')], max_length=50, null=True, verbose_name='Cancellation Reason'),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At'),
        ),
    ]
