# Generated by Django 4.2.7 on 2025-10-17 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demos', '0012_demorequest_cancellation_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='When the demo was assigned', null=True),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Admin who assigned this demo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_demos_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demorequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Employee assigned to handle this demo', limit_choices_to={'is_active': True, 'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_demo_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
