# Generated by Django 5.2.7 on 2025-10-29 16:38

import demos.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0013_demorequest_assigned_at_demorequest_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Download Count'),
        ),
        migrations.AddField(
            model_name='demo',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='Auto-calculated file size', verbose_name='File Size (bytes)'),
        ),
        migrations.AddField(
            model_name='demo',
            name='file_version',
            field=models.CharField(blank=True, help_text='Version number (optional)', max_length=50, verbose_name='File Version'),
        ),
        migrations.AddField(
            model_name='demo',
            name='lms_file',
            field=models.FileField(blank=True, help_text='Upload LMS/SCORM package (ZIP format)', null=True, upload_to=demos.models.demo_lms_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'scorm'])], verbose_name='LMS/SCORM File'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='extracted_path',
            field=models.CharField(blank=True, help_text='Path to extracted WebGL/LMS files (auto-populated)', max_length=500, verbose_name='Extracted Path'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='file_type',
            field=models.CharField(choices=[('video', 'Video'), ('webgl', 'WebGL'), ('lms', 'LMS/SCORM')], default='video', help_text='Select the type of demo content', max_length=10, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload custom thumbnail (optional - default icon will be shown if not provided)', null=True, upload_to=demos.models.demo_thumbnail_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Thumbnail Image'),
        ),
    ]
