# Generated by Django 5.2.7 on 2025-10-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0014_demo_download_count_demo_file_size_demo_file_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='demo_type',
            field=models.CharField(blank=True, choices=[('product', 'Product Demo'), ('feature', 'Feature Demo'), ('overview', 'Overview Demo'), ('tutorial', 'Tutorial'), ('case_study', 'Case Study'), ('webinar', 'Webinar Recording')], default='product', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='demo',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sort Order'),
        ),
    ]
