# Generated by Django 4.2.7 on 2025-10-13 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminColumnPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(choices=[('customers', 'Customers List'), ('demos', 'Demos List'), ('demo_requests', 'Demo Requests List'), ('enquiries', 'Enquiries List'), ('categories', 'Categories List')], max_length=50, verbose_name='Table Name')),
                ('visible_columns', models.JSONField(default=list, help_text='List of column identifiers that are visible', verbose_name='Visible Columns')),
                ('column_order', models.JSONField(blank=True, default=list, help_text='Order of columns', verbose_name='Column Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Admin Column Preference',
                'verbose_name_plural': 'Admin Column Preferences',
                'db_table': 'admin_column_preferences',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'table_name')},
            },
        ),
    ]
