# Generated by Django 4.2.7 on 2025-09-26 04:57

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[accounts.models.validate_business_email], verbose_name='Business Email')),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')], verbose_name='Mobile Number')),
                ('country_code', models.CharField(choices=[('+91', '🇮🇳 India (+91)'), ('+1', '🇺🇸 USA (+1)'), ('+44', '🇬🇧 UK (+44)'), ('+86', '🇨🇳 China (+86)'), ('+49', '🇩🇪 Germany (+49)')], default='+91', max_length=5, verbose_name='Country Code')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Job Title')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='Organization')),
                ('referral_source', models.CharField(blank=True, choices=[('referral', 'Referral from colleague'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('google', 'Google Search'), ('other', 'Other')], max_length=20, verbose_name='How did you find us?')),
                ('referral_message', models.TextField(blank=True, verbose_name='Additional Message')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Account Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'demo_portal_users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
