# Generated by Django 4.2.7 on 2025-10-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role_customuser_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Permission Name')),
                ('codename', models.CharField(help_text='e.g., view_customers, edit_demos', max_length=100, unique=True, verbose_name='Code Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('module', models.CharField(choices=[('customers', 'Customer Management'), ('demos', 'Demo Management'), ('demo_requests', 'Demo Requests'), ('enquiries', 'Enquiries'), ('notifications', 'Notifications'), ('business_categories', 'Business Categories'), ('settings', 'Settings'), ('analytics', 'Analytics & Reports'), ('system', 'System Administration')], max_length=50, verbose_name='Module')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'rbac_permissions',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-priority', 'name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registered_ip',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reports_to',
        ),
        migrations.RemoveField(
            model_name='role',
            name='display_name',
        ),
        migrations.AddField(
            model_name='role',
            name='is_system_role',
            field=models.BooleanField(default=False, help_text='System roles cannot be deleted (Super Admin, Admin, etc.)', verbose_name='System Role'),
        ),
        migrations.AddField(
            model_name='role',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher priority = more access (used for hierarchy)', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, help_text="User's primary role in the system", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Role Name'),
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AlterModelTable(
            name='role',
            table='rbac_roles',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddField(
            model_name='customuser',
            name='additional_permissions',
            field=models.ManyToManyField(blank=True, help_text='Extra permissions beyond role permissions', related_name='users_with_permission', to='accounts.permission', verbose_name='Additional Permissions'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='accounts.permission', verbose_name='Permissions'),
        ),
    ]
