# Generated by Django 4.2.7 on 2025-10-15 13:39

import accounts.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_permission_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique employee identifier (e.g., EMP001)', max_length=50, null=True, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='system_mac_address',
            field=models.CharField(blank=True, help_text="Auto-captured from user's system (Format: XX:XX:XX:XX:XX:XX)", max_length=17, null=True, verbose_name='System MAC Address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('customer', 'Customer')], default='customer', max_length=10, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='additional_permissions',
            field=models.ManyToManyField(blank=True, related_name='users_with_permission', to='accounts.permission', verbose_name='Additional Permissions'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='business_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.businesscategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='business_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.businesssubcategory', verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[accounts.models.validate_business_email], verbose_name='Office Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive users cannot login to the system', verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Auto-captured on login', null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('referral', 'Referral from colleague'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('google', 'Google Search'), ('other', 'Other')], max_length=20, verbose_name='Referral Source'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Admin, Sales, Manager, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role', verbose_name='Role'),
        ),
    ]
