# Generated by Django 5.2.7 on 2025-11-13 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be between 7-15 digits.', regex='^\\d{7,15}$')], verbose_name='Contact Number'),
        ),
    ]
