# Generated by Django 4.2.7 on 2025-10-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessenquiry',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload file (PNG, WEBP, JPG, PDF, Excel, CSV, PSD). Max 10MB', null=True, upload_to='enquiry_attachments/%Y/%m/', verbose_name='Attachment'),
        ),
    ]
