# Generated by Django 4.2.7 on 2025-09-27 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('screenshot_attempt', 'Screenshot Attempt'), ('devtools_detected', 'Developer Tools Detected'), ('context_menu', 'Right Click Menu'), ('copy_attempt', 'Copy Attempt'), ('print_attempt', 'Print Attempt'), ('drag_attempt', 'Drag & Drop Attempt'), ('screen_recording', 'Screen Recording Attempt'), ('suspicious_navigation', 'Suspicious Navigation'), ('multiple_sessions', 'Multiple Active Sessions')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('page_url', models.URLField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('action_taken', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_violations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('suspicious_activity', models.BooleanField(default=False)),
                ('security_violations', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('demo_view', 'Demo View'), ('demo_like', 'Demo Like'), ('demo_request', 'Demo Request'), ('enquiry_sent', 'Enquiry Sent'), ('security_violation', 'Security Violation'), ('suspicious_activity', 'Suspicious Activity')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_type'], name='customer_ac_user_id_646482_idx'), models.Index(fields=['created_at'], name='customer_ac_created_d09c4f_idx')],
            },
        ),
    ]
