# Generated by Django 4.2.7 on 2025-09-27 12:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customersession',
            unique_together={('user', 'session_key')},
        ),
    ]
