# Generated by Django 4.2.7 on 2025-09-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_fix_session_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('demo_view', 'Demo View'), ('demo_like', 'Demo Like'), ('demo_request', 'Demo Request'), ('demo_request_cancelled', 'Demo Request Cancelled'), ('enquiry_sent', 'Enquiry Sent'), ('security_violation', 'Security Violation'), ('suspicious_activity', 'Suspicious Activity')], max_length=30),
        ),
    ]
