# Generated by Django 4.2.7 on 2025-09-26 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('notification_type', models.CharField(choices=[('demo_confirmation', 'Demo Confirmation'), ('demo_reschedule', 'Demo Reschedule'), ('demo_cancellation', 'Demo Cancellation'), ('enquiry_received', 'Enquiry Received'), ('enquiry_response', 'Enquiry Response'), ('new_demo_available', 'New Demo Available'), ('account_approved', 'Account Approved'), ('system_announcement', 'System Announcement')], max_length=30, unique=True, verbose_name='Notification Type')),
                ('email_subject', models.CharField(max_length=200, verbose_name='Email Subject')),
                ('email_body', models.TextField(help_text='Use {{variable_name}} for dynamic content', verbose_name='Email Body')),
                ('title_template', models.CharField(help_text='Use {{variable_name}} for dynamic content', max_length=200, verbose_name='In-App Title')),
                ('message_template', models.TextField(help_text='Use {{variable_name}} for dynamic content', verbose_name='In-App Message')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('send_email', models.BooleanField(default=True, verbose_name='Send Email')),
                ('send_in_app', models.BooleanField(default=True, verbose_name='Send In-App')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('announcement_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('maintenance', 'Maintenance')], default='info', max_length=20, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('show_on_login', models.BooleanField(default=False, verbose_name='Show on Login')),
                ('show_on_dashboard', models.BooleanField(default=True, verbose_name='Show on Dashboard')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'System Announcement',
                'verbose_name_plural': 'System Announcements',
                'db_table': 'system_announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('demo_confirmation', 'Demo Confirmation'), ('demo_reschedule', 'Demo Reschedule'), ('demo_cancellation', 'Demo Cancellation'), ('enquiry_received', 'Enquiry Received'), ('enquiry_response', 'Enquiry Response'), ('new_demo_available', 'New Demo Available'), ('account_approved', 'Account Approved'), ('system_announcement', 'System Announcement')], max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email Sent')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True, verbose_name='Email Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_7336fd_idx')],
            },
        ),
    ]
