# Generated by Django 4.2.7 on 2025-10-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('demo_confirmation', 'Demo Confirmation'), ('demo_reschedule', 'Demo Reschedule'), ('demo_cancellation', 'Demo Cancellation'), ('demo_rejection', 'Demo Rejection'), ('enquiry_received', 'Enquiry Received'), ('enquiry_response', 'Enquiry Response'), ('enquiry_status', 'Enquiry Status Change'), ('new_demo_available', 'New Demo Available'), ('account_approved', 'Account Approved'), ('account_blocked', 'Account Blocked'), ('account_unblocked', 'Account Unblocked'), ('password_reset', 'Password Reset'), ('profile_updated', 'Profile Updated'), ('system_announcement', 'System Announcement'), ('new_customer', 'New Customer Registration'), ('demo_request', 'New Demo Request'), ('demo_request_cancelled', 'Demo Request Cancelled by Customer'), ('enquiry', 'New Business Enquiry'), ('milestone', 'System Milestone')], max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('demo_confirmation', 'Demo Confirmation'), ('demo_reschedule', 'Demo Reschedule'), ('demo_cancellation', 'Demo Cancellation'), ('demo_rejection', 'Demo Rejection'), ('enquiry_received', 'Enquiry Received'), ('enquiry_response', 'Enquiry Response'), ('enquiry_status', 'Enquiry Status Change'), ('new_demo_available', 'New Demo Available'), ('account_approved', 'Account Approved'), ('account_blocked', 'Account Blocked'), ('account_unblocked', 'Account Unblocked'), ('password_reset', 'Password Reset'), ('profile_updated', 'Profile Updated'), ('system_announcement', 'System Announcement'), ('new_customer', 'New Customer Registration'), ('demo_request', 'New Demo Request'), ('demo_request_cancelled', 'Demo Request Cancelled by Customer'), ('enquiry', 'New Business Enquiry'), ('milestone', 'System Milestone')], max_length=30, unique=True, verbose_name='Notification Type'),
        ),
    ]
